#!/bin/bash
result=$(nmcli -t -f type,state,connection d | egrep "^(tun|tap):connected" | awk -F':' '{ print $3 }')
[[ -z $result ]] && echo '<span foreground="#FF0000">down</span>' || echo '<span foreground="green">connected</span>'
